- name: Initialize Docker Swarm
  hosts: manager
  become: yes

  tasks:
  - name: Docker Swarm initialize
    shell: docker swarm init
    register: token # register shell komutunun sonucunu bir degiskene(burda token) atiyor, burdaki token herhangi bir sey olarak tanimlanabilir asagida bunu kullaniyoruz

  - name: Docker Swarm token
    debug: # debug komutunu ciktiyi birkac satirda verir
      var: token.stdout_lines
