- name: install docker and configure
  hosts: _development
  become: true
  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest 
    # we may need to uninstall any existing docker files from the centos repo first. 

    - name: remove old docker packages
      ansible.builtin.yum:
        name: 
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
        state: removed

    - name: Install yum utils
      ansible.builtin.yum:
        name: "yum-utils"
        state: latest
    # yum-utils is a collection of tools and programs for managing yum repositories, installing debug packages, source packages, extended information from repositories and administration.

    - name : Add docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      ansible.builtin.package: # isletim sistemini anliyor ve ona gore yukleme yapiyor
        name: docker-ce
        state: latest

    - name: add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes # "usermod -a -G docker ec2-user" yes demez isek ec2-user i docker grubuna ekliyor fakat diger gruplardan cikartiyor / eski gruplardan silme    

    - name: start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes